// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6W8iTAsypo72yqT_pkljXuhTv1RGutn8',
    appId: '1:1079643334097:web:a04b9f9952e033629decf0',
    messagingSenderId: '1079643334097',
    projectId: 'video-project-39c3e',
    authDomain: 'video-project-39c3e.firebaseapp.com',
    storageBucket: 'video-project-39c3e.appspot.com',
    measurementId: 'G-Q1P9Y4424G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvfQsAIyM3xISr6YIC-m9LJMe3lTyU6c',
    appId: '1:1079643334097:android:91b4a06296286a489decf0',
    messagingSenderId: '1079643334097',
    projectId: 'video-project-39c3e',
    storageBucket: 'video-project-39c3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ncJlMKcPQ8DFdrUvQN8oAJJor5mVSGw',
    appId: '1:1079643334097:ios:1436321ed20cdf7e9decf0',
    messagingSenderId: '1079643334097',
    projectId: 'video-project-39c3e',
    storageBucket: 'video-project-39c3e.appspot.com',
    iosBundleId: 'com.example.shorts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ncJlMKcPQ8DFdrUvQN8oAJJor5mVSGw',
    appId: '1:1079643334097:ios:1436321ed20cdf7e9decf0',
    messagingSenderId: '1079643334097',
    projectId: 'video-project-39c3e',
    storageBucket: 'video-project-39c3e.appspot.com',
    iosBundleId: 'com.example.shorts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6W8iTAsypo72yqT_pkljXuhTv1RGutn8',
    appId: '1:1079643334097:web:26853cf284f2992f9decf0',
    messagingSenderId: '1079643334097',
    projectId: 'video-project-39c3e',
    authDomain: 'video-project-39c3e.firebaseapp.com',
    storageBucket: 'video-project-39c3e.appspot.com',
    measurementId: 'G-F16RTQPCNM',
  );
}
